# This is a basic workflow to help you get started with Actions

name: Install-CI
on: [push, pull_request, workflow_dispatch]
defaults:
  run:
    shell: zsh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - run: source install.sh
