# This is a basic workflow to help you get started with Actions

name: Install-CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: zsh {0}
    steps:
      - uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - run: rm ~/.zshrc
      - run: source install.sh
