# This is a basic workflow to help you get started with Actions

name: Install-CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install zsh
      - run: sudo chsh -s $(which zsh)
      - run: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - run: rm ~/.zshrc
      - run: source install.sh
